# permissions to do viewer horizontaldigdagworkerautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: horizontaldigdagworkerautoscaler-viewer-role
rules:
- apiGroups:
  - horizontalpodautoscalers.autoscaling.digdag-worker-crd
  resources:
  - horizontaldigdagworkerautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - horizontalpodautoscalers.autoscaling.digdag-worker-crd
  resources:
  - horizontaldigdagworkerautoscalers/status
  verbs:
  - get
